PaySmart Native Bridges: room Namespace Reference
room Namespace Reference
Derives a key using PBKDF2-HMAC-SHA256.
Functions
bool is_valid_aes_key_size (size_t keySize)
const EVP_CIPHER * select_cipher (size_t keySize)
std::string encrypt_string (const std::string &plaintext, const std::string &keyHex)
std::string decrypt_string (const std::string &input, const std::string &keyHex)
std::vector< uint8_t > pbkdf2_sha256 (const std::string &password, const std::vector< uint8_t > &salt, int iterations, int keyLength)
Variables
constexpr size_t IV_SIZE = 12
constexpr size_t TAG_SIZE = 16
Detailed Description
Derives a key using PBKDF2-HMAC-SHA256.
Parameters
password Plaintext password
salt Random salt bytes
iterations Number of PBKDF2 iterations
keyLength Desired output key length in bytes
Returns
Derived key as a vector of bytes
Function Documentation
decrypt_string()
std::string room::decrypt_string (const std::string & input, const std::string & keyHex)
Definition at line 92 of file aes_encryptor.cpp.
References is_valid_aes_key_size(), safe_size_cast(), select_cipher(), and TAG_SIZE.
Referenced by Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_decryptString().
encrypt_string()
std::string room::encrypt_string (const std::string & plaintext, const std::string & keyHex)
Definition at line 40 of file aes_encryptor.cpp.
References is_valid_aes_key_size(), IV_SIZE, safe_size_cast(), select_cipher(), and TAG_SIZE.
Referenced by Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_encryptString().
is_valid_aes_key_size()
bool room::is_valid_aes_key_size (size_t keySize)
Definition at line 28 of file aes_encryptor.cpp.
Referenced by decrypt_string(), and encrypt_string().
pbkdf2_sha256()
std::vector< uint8_t > room::pbkdf2_sha256 (const std::string & password, const std::vector< uint8_t > & salt, int iterations, int keyLength)
Definition at line 12 of file pbkdf2.cpp.
References safe_size_cast().
Referenced by Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_deriveRoomKey().
select_cipher()
const EVP_CIPHER * room::select_cipher (size_t keySize)
Definition at line 32 of file aes_encryptor.cpp.
Referenced by decrypt_string(), and encrypt_string().
Variable Documentation
IV_SIZE
constexpr size_t room::IV_SIZE = 12 constexpr
Definition at line 23 of file aes_encryptor.cpp.
Referenced by encrypt_string().
TAG_SIZE
constexpr size_t room::TAG_SIZE = 16 constexpr
Definition at line 24 of file aes_encryptor.cpp.
Referenced by decrypt_string(), and encrypt_string().