PaySmart Native Bridges: room-lib.cpp File Reference
room-lib.cpp File Reference
#include "room/pbkdf2.h"
#include "room/aes_encryptor.h"
#include <jni.h>
#include <string>
#include <vector>
Functions
JNIEXPORT jstring JNICALL Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_encryptString (JNIEnv *env, jclass clazz, jstring plain, jstring key)
JNIEXPORT jstring JNICALL Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_decryptString (JNIEnv *env, jclass clazz, jstring cipher, jstring key)
Decrypts a Room payload previously encrypted via AES-GCM in the JNI layer.
JNIEXPORT jbyteArray JNICALL Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_deriveRoomKey (JNIEnv *env, jclass thiz, jstring passphrase, jbyteArray salt, jint iterations, jint keyLen)
Derives a Room encryption key from passphrase + salt using PBKDF2-SHA256.
Function Documentation
Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_decryptString()
JNIEXPORT jstring JNICALL Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_decryptString (JNIEnv * env, jclass clazz, jstring cipher, jstring key)
Decrypts a Room payload previously encrypted via AES-GCM in the JNI layer.
Definition at line 52 of file room-lib.cpp.
References room::decrypt_string().
Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_deriveRoomKey()
JNIEXPORT jbyteArray JNICALL Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_deriveRoomKey (JNIEnv * env, jclass thiz, jstring passphrase, jbyteArray salt, jint iterations, jint keyLen)
Derives a Room encryption key from passphrase + salt using PBKDF2-SHA256.
Definition at line 90 of file room-lib.cpp.
References room::pbkdf2_sha256().
Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_encryptString()
JNIEXPORT jstring JNICALL Java_net_metalbrain_paysmart_data_native_RoomNativeBridge_encryptString (JNIEnv * env, jclass clazz, jstring plain, jstring key)
Definition at line 14 of file room-lib.cpp.
References room::encrypt_string().