export const API_FUNCTION_SECRETS = [
    "RESEND_API_KEY",
    "ADDRESS_VALIDATION_API_KEY",
    "EXCHANGE_RATE_API_KEY",
    "STRIPE_SECRET_KEY",
    "STRIPE_PUBLISHABLE_KEY",
    "STRIPE_WEBHOOK_SECRET",
    "FLUTTERWAVE_SECRET_KEY",
    "FLUTTERWAVE_PUBLIC_KEY",
    "FLUTTERWAVE_WEBHOOK_SECRET_HASH",
    "FLUTTERWAVE_CLIENT_ID",
    "FLUTTERWAVE_CLIENT_SECRET",
    "INVOICE_PDF_TASK_TOKEN",
];
//# sourceMappingURL=functionSecrets.js.map