package net.metalbrain.paysmart.core.invoice.model

object InvoiceFieldKeys {
    const val INVOICE_NUMBER = "invoice_number"
    const val INVOICE_DATE = "invoice_date"
    const val WEEK_ENDING = "week_ending"
    const val WORKER_NAME = "worker_name"
    const val WORKER_ADDRESS = "worker_address"
    const val WORKER_BADGE_NUMBER = "worker_badge_number"
    const val WORKER_BADGE_EXPIRY = "worker_badge_expiry"
    const val WORKER_UTR = "worker_utr"
    const val WORKER_EMAIL = "worker_email"
    const val WORKER_PHONE = "worker_phone"
    const val PAYMENT_ACCOUNT_NUMBER = "payment_account_number"
    const val PAYMENT_SORT_CODE = "payment_sort_code"
    const val PAYMENT_INSTRUCTIONS = "payment_instructions"
    const val DEFAULT_RATE = "default_rate"
    const val CLIENT_NAME = "client_name"
    const val CLIENT_ADDRESS = "client_address"
    const val CLIENT_COUNTRY = "client_country"
    const val SITE_LOCATION = "site_location"
    const val SHIFT_TYPE = "shift_type"
    const val WARD = "ward"
    const val NHS_BAND = "nhs_band"
    const val PROJECT_NAME = "project_name"
    const val DESCRIPTION = "description"
    const val INCIDENT_NOTES = "incident_notes"
    const val LINE_DATE = "line_date"
    const val LINE_TASK = "line_task"
    const val LINE_HOURS = "line_hours"
    const val LINE_RATE = "line_rate"
    const val LINE_AMOUNT = "line_amount"
    const val LINE_SHIFT_TYPE = "line_shift_type"
    const val LINE_BONUS = "line_bonus"
}
