PaySmart Native Bridges: app/src/main/cpp/native-lib.cpp File Reference
native-lib.cpp File Reference
#include "crypto/pbkdf2.h"
#include "crypto/password_hasher.h"
#include <jni.h>
#include <string>
#include <vector>
Functions
JNIEXPORT jbyteArray JNICALL Java_net_metalbrain_paysmart_data_native_NativeBridge_deriveKeyFromCpp (JNIEnv *env, jclass, jstring password, jbyteArray salt, jint iterations, jint keyLength)
Derives a key using PBKDF2-SHA256 for app-side crypto operations.
JNIEXPORT jstring JNICALL Java_net_metalbrain_paysmart_data_native_NativePasswordBridge_hashPassword (JNIEnv *env, jclass, jstring password)
Hashes a password using the native password hasher implementation.
JNIEXPORT jboolean JNICALL Java_net_metalbrain_paysmart_data_native_NativePasswordBridge_verifyPassword (JNIEnv *env, jclass, jstring password, jstring storedHash)
Verifies a plaintext password against a previously computed native hash.
Function Documentation
Java_net_metalbrain_paysmart_data_native_NativeBridge_deriveKeyFromCpp()
JNIEXPORT jbyteArray JNICALL Java_net_metalbrain_paysmart_data_native_NativeBridge_deriveKeyFromCpp (JNIEnv * env, jclass , jstring password, jbyteArray salt, jint iterations, jint keyLength)
Derives a key using PBKDF2-SHA256 for app-side crypto operations.
Definition at line 16 of file native-lib.cpp.
References crypto::pbkdf2_sha256().
Java_net_metalbrain_paysmart_data_native_NativePasswordBridge_hashPassword()
JNIEXPORT jstring JNICALL Java_net_metalbrain_paysmart_data_native_NativePasswordBridge_hashPassword (JNIEnv * env, jclass , jstring password)
Hashes a password using the native password hasher implementation.
Definition at line 46 of file native-lib.cpp.
References crypto::hash_password().
Java_net_metalbrain_paysmart_data_native_NativePasswordBridge_verifyPassword()
JNIEXPORT jboolean JNICALL Java_net_metalbrain_paysmart_data_native_NativePasswordBridge_verifyPassword (JNIEnv * env, jclass , jstring password, jstring storedHash)
Verifies a plaintext password against a previously computed native hash.
Definition at line 63 of file native-lib.cpp.
References crypto::verify_password().